version: "2.1"
services:
  jellyfin:
    image: docker.io/mpepping/cyberchef:latest
    container_name: cyberchef
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    ports:
      - 8001:8000
    restart: unless-stopped

