version: "2.1"
services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - /opt/appdata/prometheus:/etc/prometheus
    ports:
      - 9092:9090
    restart: unless-stopped

