version: "3"

# Passing no environment variables since container doesn't use them
services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      # Using regular volume to have data persistency and avoid messing with
      # permissions
      - prometheus:/prometheus
    ports:
      - 9092:9090
    restart: "${RESTART_POLICY}"

volumes:
  prometheus:

