version: "3"

services:
  jellyfin:
    image: docker.io/mpepping/cyberchef:latest
    container_name: cyberchef
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    ports:
      - 8001:8000
    restart: "${RESTART_POLICY}"

