version: "3"

services:
  grafana:
    image: docker.io/grafana/grafana-oss:latest
    container_name: grafana
    user: "0:0"
    extends:
      file: ../base.yml
      service: base_service
    volumes:
      - /opt/appdata/grafana:/var/lib/grafana
    ports:
      - 3030:3000

