version: "3"

services:
  grafana:
    image: docker.io/grafana/grafana-oss:latest
    container_name: grafana
    user: "0:0"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${VOLUME_PREFIX}/grafana:/var/lib/grafana"
    ports:
      - 3030:3000
    restart: "${RESTART_POLICY}"

