version: "3"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    extends:
      file: ../base.yml
      service: base_service
    volumes:
      - /opt/appdata/homepage:/app/config
      - $XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock
    ports:
      - 3000:3000

