version: "3"

services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${VOLUME_PREFIX}/nginx:/config"
    ports:
      - 80:80
      - 443:443
    restart: "${RESTART_POLICY}"

