version: "3"

services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${VOLUME_PREFIX}/prometheus:/etc/prometheus"
    ports:
      - 9092:9090
    restart: "${RESTART_POLICY}"

