version: "3"

services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    extends:
      file: ../base.yml
      service: base_service
    volumes:
      - /opt/appdata/nginx:/config
    ports:
      - 80:80
      - 443:443

