version: "3"

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    extends:
      file: ../base.yml
      service: base_service
    volumes:
      - /opt/appdata/syncthing:/config
    ports:
      - 8384:8384
      - 22000:22000
      - 22000:22000/udp
      - 21027:21027/udp

